name: Segundo Uno
favicon: null
layout_spectrum: 0.94112
typography_spectrum: 0.16058
title: Segundo Uno
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#050304'
    - '#ffffff'
    - '#6f5e54'
    - '#a7846e'
    - '#969fbc'
  brandStrength: 0.6875
  lightness: 0.6875
  saturation: 0.3125
  rhythmicContrast: 1
purpose: []
