name: Segundo 1
favicon: null
layout_spectrum: 0.9142739053349942
typography_spectrum: 0.3156882058829069
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.8506610027980059
  lightness: 0.25176642392762005
  saturation: 0.3723615847993642
  rhythmicContrast: 0.7241984547581524
purpose: []
